apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../manifests/namespace
- ../manifests/local-storage
- manifests/prometheus
- manifests/grafana
- manifests/kube-state-metrics
- manifests/node-exporter
images:
- name: registry.k8s.io/kube-state-metrics/kube-state-metrics
  newTag: v2.15.0
- name: prom/prometheus
  newTag: v3.2.1
- name: prom/node-exporter
  newTag: v1.9.0
- name: grafana/grafana-oss
  newTag: 11.3.4 
