apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics
resources:
- manifests/deployment.yaml
- manifests/service.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: metrics
