apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics
resources:
- manifests/rbac.yaml
- manifests/deployment.yaml
- manifests/service.yaml
configMapGenerator:
- files:
  - manifests/config/prometheus.yaml
  name: prometheus-configuration
generatorOptions:
  disableNameSuffixHash: true
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: metrics
